<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('motors')->insert([
            [
                'order' => 1,
                'kode_nosin' => 'JBP1E',
                'type_motor' => 'Supra X 125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 2,
                'kode_nosin' => 'JBN1E',
                'type_motor' => 'Supra X 125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 3,
                'kode_nosin' => 'JBK1E',
                'type_motor' => 'Revo X dan Revo Fit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 4,
                'kode_nosin' => 'JBK3E',
                'type_motor' => 'Revo X dan Revo Fit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 5,
                'kode_nosin' => 'JM81E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 6,
                'kode_nosin' => 'JM82E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 7,
                'kode_nosin' => 'JM91E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 8,
                'kode_nosin' => 'JME1E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 9,
                'kode_nosin' => 'JMF1E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 10,
                'kode_nosin' => 'JMF2E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 11,
                'kode_nosin' => 'JMG1E',
                'type_motor' => 'Beat & Beat Street',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 12,
                'kode_nosin' => 'JMC1E',
                'type_motor' => 'Vario 125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 13,
                'kode_nosin' => 'JMD1E',
                'type_motor' => 'Vario 125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 14,
                'kode_nosin' => 'KFA1E',
                'type_motor' => 'Vario 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 15,
                'kode_nosin' => 'KF01E',
                'type_motor' => 'Vario 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 16,
                'kode_nosin' => 'KFC1E',
                'type_motor' => 'Stylo 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 17,
                'kode_nosin' => 'KFD1E',
                'type_motor' => 'Stylo 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 18,
                'kode_nosin' => 'JM03E',
                'type_motor' => 'Scoopy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 19,
                'kode_nosin' => 'JM04E',
                'type_motor' => 'Scoopy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 20,
                'kode_nosin' => 'JMH1E',
                'type_motor' => 'Scoopy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 21,
                'kode_nosin' => 'JMH2E',
                'type_motor' => 'Scoopy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 22,
                'kode_nosin' => 'JMA1E',
                'type_motor' => 'Genio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 23,
                'kode_nosin' => 'JMB1E',
                'type_motor' => 'Genio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 24,
                'kode_nosin' => 'KFB1E',
                'type_motor' => 'ADV 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 25,
                'kode_nosin' => 'KFB2E',
                'type_motor' => 'ADV 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 26,
                'kode_nosin' => 'KB22E',
                'type_motor' => 'Supra GTR 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 27,
                'kode_nosin' => 'KB11E',
                'type_motor' => 'Sonic 150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 28,
                'kode_nosin' => 'KD11E',
                'type_motor' => 'CRF 150L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 29,
                'kode_nosin' => 'KF71E',
                'type_motor' => 'PCX 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 30,
                'kode_nosin' => 'KF81E',
                'type_motor' => 'PCX 160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 31,
                'kode_nosin' => 'KFE1E',
                'type_motor' => 'PCX 160 - CBS ABS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 32,
                'kode_nosin' => 'KFE2E',
                'type_motor' => 'PCX 160 - CBS ABS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 33,
                'kode_nosin' => 'KFE3E',
                'type_motor' => 'PCX 160 - ROADSYNX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 34,
                'kode_nosin' => 'KCD1E',
                'type_motor' => 'CB150 Streetfire',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 35,
                'kode_nosin' => 'KCD2E',
                'type_motor' => 'CB150 Streetfire',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 36,
                'kode_nosin' => 'KCE1E',
                'type_motor' => 'CB150X',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 37,
                'kode_nosin' => 'KC01E',
                'type_motor' => 'CB150 Verza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 38,
                'kode_nosin' => 'KC02E',
                'type_motor' => 'CB150 Verza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 39,
                'kode_nosin' => 'KC04E',
                'type_motor' => 'CB150 Verza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 40,
                'kode_nosin' => 'KCB1E',
                'type_motor' => 'CB150R',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 41,
                'kode_nosin' => 'KCC1E',
                'type_motor' => 'CB150R',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 42,
                'kode_nosin' => 'EF21E',
                'type_motor' => 'EM1 e: & EM1 e: PLUS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order' => 43,
                'kode_nosin' => 'EF22E',
                'type_motor' => 'EM1 e: & EM1 e: PLUS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
